### ISSUE TITLE
Deadlock in multiproccessing

### ISSUE THREAD

**Issue by leonard-creator** [micahvista/MAMnet#8]
Hi, I am currently testing MAMnet and have got it working. Unfortunatelly, it gets stuck in the while loop ( line 643 ), and waits for childprocesses that dont seem to exist or never finish. Therefore, the calculated result is never written to a vcf file. 

<img width="284" alt="endles_loop" src="https://github.com/micahvista/MAMnet/assets/80115155/18fea8ba-3a3d-4851-83a0-b4bc2ec53b6b">

I encountered this while using -threads 1 and - threads >=2 and it seems to be a problem of the multiprocessing code. 

<img width="952" alt="MAMnet_runtime" src="https://github.com/micahvista/MAMnet/assets/80115155/9b60bf57-13e3-4c9d-865b-5da0f41607dc">

Another thing that I noticed is when killing the process with ctr-C it terminates, but there is still another process running and I have to kill it by addressing it with `kill pid` and passing the exact process id.

<img width="632" alt="Error_after_kill" src="https://github.com/micahvista/MAMnet/assets/80115155/373045d0-49aa-46fc-bb86-98e161bffb45">

Thats the error that appears after terminating.

I am using a small test bam file containing only chr9 data with calculated MD-tags with the default parameter of MAMnet on a linux -Ubuntu x86_64 server and MAMnet in a conda environment. 

The only thing I altered without success regarding the multiprocessing documentation is adding the `if __name__ == '__main__':` line in MAMnet.py

**Comment by micahvista** [comment]
Dear leonard-creator:
    Can you send me a copy of the bam file, my email is micahvista747@gmail.com.  So, I can run some tests and try to locate the errors.
Thanks
Hongyu Ding

**Comment by micahvista** [comment]
Dear leonard-creator:
I just updated the code; can you try the latest version and give me feedback?
Thanks
Hongyu Ding

**Comment by leonard-creator** [comment]
Hi Hongyu Ding, 

I tryed again unfortunately still the same problem. Nothing happens after: _'Stop signal sended to callsv_. Also, it doesn't matter what number of threads I enter as parameters, the actual threads are always much more. And the problem of the program not terminating fully is also still there. 

`python MAMnet.py -bamfilepath md_bam/HG00733.svision.demo.md.bam -workdir workdir/ -outputpath results/variants.vcf -step 50 -threads 2`

`python MAMnet.py -bamfilepath md_bam/HG00733.svision.demo.md.bam -workdir workdir/ -outputpath results/variants.vcf -step 50 -threads 12`


<img width="891" alt="multiple_threads" src="https://github.com/micahvista/MAMnet/assets/80115155/4486a66f-f712-400b-969b-ea1891cd9218">

**Comment by micahvista** [comment]
Dear leonard-creator:
I am still trying to reproduce the error, once I fixed I will let you know.
Thanks.
Hongyu Ding

**Comment by leonard-creator** [comment]
Hi Hongyu Ding, 
I debugged myself and could identify the error in the call_sv function, which seems to have problems loading the model. I fear, something with my GPU-tensorflow combined settings is not right. I will investigate more and let you know as well.
